export default interface AnimeAttributes {
  createdAt: string,
  updatedAt: string,
  slug: string,
  synopsis: string,
  coverImageTopOffset: number,
  titles: {
    en?: string,
    en_jp?: string,
    ja_jp?: string,
  },
  canonicalTitle: string,
  coverImage?: {
    tiny: string,
    small: string,
    medium: string,
    large: string,
    original: string,
    meta: any,
  },
  abbreviatedTitles: string[],
  averageRating: string,
  userCount: number,
  favoritesCount: number,
  startDate: string,
  endDate: string,
  popularityRank: number,
  posterImage: {
    tiny: string,
    small: string,
    medium: string,
    large: string,
    original: string,
    meta: any,
  },
  ratingRank: number,
  ageRatingGuide: string,
  tba: string,
  episodeCount: number,
  episodeLength: number,
  youtubeVideoId: string,
}
